= Contributing

This document contains development information. It's expected that all
contributors read this documentation in its entirety before contributing to
this infrastructure provider.

== Requirements

* https://go.dev/[Go] - To build and test the infrastructure provider. Use the
version of Go specified in `go.mod`.
* https://podman.io/[Podman] or https://www.docker.com/[Docker] - To build and
run the container image. Either container runtime works.

== Development

The `Makefile` is the primary method of interfacing with this project. Refer to
its targets for more information. The build artifact is a container image to be
run wherever it'll have access to the Oxide silo it's configured to connect to.

=== Running Locally

. Export the necessary environment variables.
+
[source,shell]
----
export OMNI_ENDPOINT=https://example.na-west-1.omni.siderolabs.io:443
export OMNI_SERVICE_ACCOUNT_KEY=ZXhhbXBsZQ==
export OXIDE_HOST='https://oxide.sys.example.com'
export OXIDE_TOKEN='oxide-token-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
----

. Run the infrastructure provider.
+
[source,shell]
----
make dev
----

== Running Tests

Run the unit tests within a container.

[source,shell]
----
make test
----

== Release Process

The release process is manual and runs from a developer's workstation.

. Check out the revision to be released. Ensure the working copy is clean.

. Build the container image.
+
[source,shell]
----
RELEASE=true make build
----

. Push the container image.
+
[source,shell]
----
RELEASE=true make push
----

. Create a GitHub release.

.. Create and push a Git tag with the v-prefixed `VERSION` (e.g., v0.1.0).

.. Create the GitHub release for the newly pushed tag. Automatically generate
the release notes.

. Open a pull request that updates the `VERSION` within the `Makefile` to the
next version.
