= Oxide Omni Infrastructure Provider

The Oxide Omni infrastructure provider is used to provision Talos Linux
instances on Oxide and connect those instances to Omni where they will be
configured as nodes in a Kubernetes cluster.

== Usage

Please note the following before using the Oxide Omni infrastructure provider.

* The infrastructure provider requires Talos Linux v1.12 or greater.

* The infrastructure provider is a dynamic provider, meaning it provisions and
deprovisions Oxide instances on demand as Omni users create and scale Kubernetes
clusters.

* The infrastructure provider is designed to manage resources within a single
Oxide silo. To support multiple Oxide silos, run a separate instance of the
infrastructure provider using a different provider ID. The infrastructure
provider uses machine classes to specify the Oxide project instances are
provisioned within.

With the above noted, let's run the Oxide Omni infrastructure provider.

. Create the infrastructure provider in Omni.
+
[source,shell]
----
omnictl --omniconfig omniconfig.yaml infraprovider create oxide
----

. Export the `OMNI_ENDPOINT` and `OMNI_SERVICE_ACCOUNT_KEY` environment variables.
+
[source,shell]
----
export OMNI_ENDPOINT=https://example.na-west-1.omni.siderolabs.io:443
export OMNI_SERVICE_ACCOUNT_KEY=ZXhhbXBsZQ==
----

. Export the `OXIDE_HOST` and `OXIDE_TOKEN` environment variables.
+
[source,shell]
----
export OXIDE_HOST='https://oxide.sys.example.com'
export OXIDE_TOKEN='oxide-token-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
----

. Download the archive for your operating system and architecture from
https://github.com/oxidecomputer/omni-infra-provider-oxide/releases[GitHub
releases], then extract it.

. Run the infrastructure provider.
+
[source,shell]
----
./omni-infra-provider-oxide
----

== Development

Please refer to link:CONTRIBUTING.adoc[`CONTRIBUTING.adoc`] for development
information, including how to run the infrastructure provider locally, run the
tests, and build release artifacts.
