// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/provider/spec/machine.proto

package spec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Machine is the per-request state the infrastructure provider persists between
// provisioning steps. It records the Oxide resources created for the machine so
// deprovisioning can remain idempotent after parent-child relationships are
// removed from Oxide.
type Machine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Instance      *Instance              `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	Disks         []*Disk                `protobuf:"bytes,3,rep,name=disks,proto3" json:"disks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Machine) Reset() {
	*x = Machine{}
	mi := &file_internal_provider_spec_machine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Machine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Machine) ProtoMessage() {}

func (x *Machine) ProtoReflect() protoreflect.Message {
	mi := &file_internal_provider_spec_machine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Machine.ProtoReflect.Descriptor instead.
func (*Machine) Descriptor() ([]byte, []int) {
	return file_internal_provider_spec_machine_proto_rawDescGZIP(), []int{0}
}

func (x *Machine) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *Machine) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *Machine) GetDisks() []*Disk {
	if x != nil {
		return x.Disks
	}
	return nil
}

// Project identifies the Oxide project the machine was created in.
type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_internal_provider_spec_machine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_internal_provider_spec_machine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_internal_provider_spec_machine_proto_rawDescGZIP(), []int{1}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Instance identifies the Oxide instance created for the machine.
type Instance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_internal_provider_spec_machine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_internal_provider_spec_machine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_internal_provider_spec_machine_proto_rawDescGZIP(), []int{2}
}

func (x *Instance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Instance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Disk identifies an Oxide disk created for the machine.
type Disk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disk) Reset() {
	*x = Disk{}
	mi := &file_internal_provider_spec_machine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_provider_spec_machine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_internal_provider_spec_machine_proto_rawDescGZIP(), []int{3}
}

func (x *Disk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Disk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_internal_provider_spec_machine_proto protoreflect.FileDescriptor

const file_internal_provider_spec_machine_proto_rawDesc = "" +
	"\n" +
	"$internal/provider/spec/machine.proto\x12\x13oxide.provider.spec\"\xad\x01\n" +
	"\aMachine\x126\n" +
	"\aproject\x18\x01 \x01(\v2\x1c.oxide.provider.spec.ProjectR\aproject\x129\n" +
	"\binstance\x18\x02 \x01(\v2\x1d.oxide.provider.spec.InstanceR\binstance\x12/\n" +
	"\x05disks\x18\x03 \x03(\v2\x19.oxide.provider.spec.DiskR\x05disks\"-\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\".\n" +
	"\bInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"*\n" +
	"\x04Disk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameBKZIgithub.com/oxidecomputer/omni-infra-provider-oxide/internal/provider/specb\x06proto3"

var (
	file_internal_provider_spec_machine_proto_rawDescOnce sync.Once
	file_internal_provider_spec_machine_proto_rawDescData []byte
)

func file_internal_provider_spec_machine_proto_rawDescGZIP() []byte {
	file_internal_provider_spec_machine_proto_rawDescOnce.Do(func() {
		file_internal_provider_spec_machine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_provider_spec_machine_proto_rawDesc), len(file_internal_provider_spec_machine_proto_rawDesc)))
	})
	return file_internal_provider_spec_machine_proto_rawDescData
}

var file_internal_provider_spec_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_provider_spec_machine_proto_goTypes = []any{
	(*Machine)(nil),  // 0: oxide.provider.spec.Machine
	(*Project)(nil),  // 1: oxide.provider.spec.Project
	(*Instance)(nil), // 2: oxide.provider.spec.Instance
	(*Disk)(nil),     // 3: oxide.provider.spec.Disk
}
var file_internal_provider_spec_machine_proto_depIdxs = []int32{
	1, // 0: oxide.provider.spec.Machine.project:type_name -> oxide.provider.spec.Project
	2, // 1: oxide.provider.spec.Machine.instance:type_name -> oxide.provider.spec.Instance
	3, // 2: oxide.provider.spec.Machine.disks:type_name -> oxide.provider.spec.Disk
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_provider_spec_machine_proto_init() }
func file_internal_provider_spec_machine_proto_init() {
	if File_internal_provider_spec_machine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_provider_spec_machine_proto_rawDesc), len(file_internal_provider_spec_machine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_provider_spec_machine_proto_goTypes,
		DependencyIndexes: file_internal_provider_spec_machine_proto_depIdxs,
		MessageInfos:      file_internal_provider_spec_machine_proto_msgTypes,
	}.Build()
	File_internal_provider_spec_machine_proto = out.File
	file_internal_provider_spec_machine_proto_goTypes = nil
	file_internal_provider_spec_machine_proto_depIdxs = nil
}
