// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/provider/spec/machine.proto

package spec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Machine is the per-request state the infrastructure provider persists between
// provisioning steps. It's intentionally empty. Each step is idempotent on
// its own by querying the Oxide API for the current state of its resources, so
// there's nothing the provider needs to remember.
type Machine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Machine) Reset() {
	*x = Machine{}
	mi := &file_internal_provider_spec_machine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Machine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Machine) ProtoMessage() {}

func (x *Machine) ProtoReflect() protoreflect.Message {
	mi := &file_internal_provider_spec_machine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Machine.ProtoReflect.Descriptor instead.
func (*Machine) Descriptor() ([]byte, []int) {
	return file_internal_provider_spec_machine_proto_rawDescGZIP(), []int{0}
}

var File_internal_provider_spec_machine_proto protoreflect.FileDescriptor

const file_internal_provider_spec_machine_proto_rawDesc = "" +
	"\n" +
	"$internal/provider/spec/machine.proto\x12\x13oxide.provider.spec\"\t\n" +
	"\aMachineBKZIgithub.com/oxidecomputer/omni-infra-provider-oxide/internal/provider/specb\x06proto3"

var (
	file_internal_provider_spec_machine_proto_rawDescOnce sync.Once
	file_internal_provider_spec_machine_proto_rawDescData []byte
)

func file_internal_provider_spec_machine_proto_rawDescGZIP() []byte {
	file_internal_provider_spec_machine_proto_rawDescOnce.Do(func() {
		file_internal_provider_spec_machine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_provider_spec_machine_proto_rawDesc), len(file_internal_provider_spec_machine_proto_rawDesc)))
	})
	return file_internal_provider_spec_machine_proto_rawDescData
}

var file_internal_provider_spec_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_provider_spec_machine_proto_goTypes = []any{
	(*Machine)(nil), // 0: oxide.provider.spec.Machine
}
var file_internal_provider_spec_machine_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_provider_spec_machine_proto_init() }
func file_internal_provider_spec_machine_proto_init() {
	if File_internal_provider_spec_machine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_provider_spec_machine_proto_rawDesc), len(file_internal_provider_spec_machine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_provider_spec_machine_proto_goTypes,
		DependencyIndexes: file_internal_provider_spec_machine_proto_depIdxs,
		MessageInfos:      file_internal_provider_spec_machine_proto_msgTypes,
	}.Build()
	File_internal_provider_spec_machine_proto = out.File
	file_internal_provider_spec_machine_proto_goTypes = nil
	file_internal_provider_spec_machine_proto_depIdxs = nil
}
