// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/provider/spec/machine.proto

package spec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Machine struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uuid             string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	InstanceId       string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ImageId          string                 `protobuf:"bytes,3,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	ImageName        string                 `protobuf:"bytes,4,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	TalosSchematicId string                 `protobuf:"bytes,5,opt,name=talos_schematic_id,json=talosSchematicId,proto3" json:"talos_schematic_id,omitempty"`
	TalosImageUrl    string                 `protobuf:"bytes,6,opt,name=talos_image_url,json=talosImageUrl,proto3" json:"talos_image_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Machine) Reset() {
	*x = Machine{}
	mi := &file_internal_provider_spec_machine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Machine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Machine) ProtoMessage() {}

func (x *Machine) ProtoReflect() protoreflect.Message {
	mi := &file_internal_provider_spec_machine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Machine.ProtoReflect.Descriptor instead.
func (*Machine) Descriptor() ([]byte, []int) {
	return file_internal_provider_spec_machine_proto_rawDescGZIP(), []int{0}
}

func (x *Machine) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Machine) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Machine) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *Machine) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *Machine) GetTalosSchematicId() string {
	if x != nil {
		return x.TalosSchematicId
	}
	return ""
}

func (x *Machine) GetTalosImageUrl() string {
	if x != nil {
		return x.TalosImageUrl
	}
	return ""
}

var File_internal_provider_spec_machine_proto protoreflect.FileDescriptor

const file_internal_provider_spec_machine_proto_rawDesc = "" +
	"\n" +
	"$internal/provider/spec/machine.proto\x12\x13oxide.provider.spec\"\xce\x01\n" +
	"\aMachine\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x19\n" +
	"\bimage_id\x18\x03 \x01(\tR\aimageId\x12\x1d\n" +
	"\n" +
	"image_name\x18\x04 \x01(\tR\timageName\x12,\n" +
	"\x12talos_schematic_id\x18\x05 \x01(\tR\x10talosSchematicId\x12&\n" +
	"\x0ftalos_image_url\x18\x06 \x01(\tR\rtalosImageUrlBKZIgithub.com/oxidecomputer/omni-infra-provider-oxide/internal/provider/specb\x06proto3"

var (
	file_internal_provider_spec_machine_proto_rawDescOnce sync.Once
	file_internal_provider_spec_machine_proto_rawDescData []byte
)

func file_internal_provider_spec_machine_proto_rawDescGZIP() []byte {
	file_internal_provider_spec_machine_proto_rawDescOnce.Do(func() {
		file_internal_provider_spec_machine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_provider_spec_machine_proto_rawDesc), len(file_internal_provider_spec_machine_proto_rawDesc)))
	})
	return file_internal_provider_spec_machine_proto_rawDescData
}

var file_internal_provider_spec_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_provider_spec_machine_proto_goTypes = []any{
	(*Machine)(nil), // 0: oxide.provider.spec.Machine
}
var file_internal_provider_spec_machine_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_provider_spec_machine_proto_init() }
func file_internal_provider_spec_machine_proto_init() {
	if File_internal_provider_spec_machine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_provider_spec_machine_proto_rawDesc), len(file_internal_provider_spec_machine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_provider_spec_machine_proto_goTypes,
		DependencyIndexes: file_internal_provider_spec_machine_proto_depIdxs,
		MessageInfos:      file_internal_provider_spec_machine_proto_msgTypes,
	}.Build()
	File_internal_provider_spec_machine_proto = out.File
	file_internal_provider_spec_machine_proto_goTypes = nil
	file_internal_provider_spec_machine_proto_depIdxs = nil
}
